const String baseUrl = 'http://api.openweathermap.org/data/2.5/forecast';

const String brokenClouds = 'assets/images/broken_clouds.jpg' ;
const String clearSky = 'assets/images/clear_sky.jpg' ;
const String day = 'assets/images/day.jpg';
const String night = 'assets/images/night.jpg';
const String rainDrops = 'assets/images/raindrops.jpg' ;
const String rainyClouds= 'assets/images/rainy_clouds.jpg' ;
const String blockedSky= 'assets/images/blocked_sky.jpg' ;
const String clearNight= 'assets/images/clear_night.jpg' ;
const String rainyDay= 'assets/images/raindrops.jpg' ;
const String country= 'assets/images/country.png' ;
const String ground= 'assets/images/ground.png' ;
const String humidityLevel= 'assets/images/humidity.png' ;
const String pressureLevel= 'assets/images/pressure.png' ;
const String sea= 'assets/images/sea_level.png' ;
const String sunRise= 'assets/images/sunrise.png' ;
const String sunSet= 'assets/images/sunset.png' ;
const String population= 'assets/images/population.png' ;